version: '3.7'

services:
  dnsrobocert:
    image: ${DOCKER_IMAGE:-adferrand/dnsrobocert}
    container_name: dnsrobocert
    env_file: .env
    volumes:
    - $ROOT/letsencrypt:/etc/letsencrypt
    - $ROOT/dnsrobocert:/etc/dnsrobocert
    environment:
    - VERSION=latest
    restart: always
