name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.11", "3.13"]
        toxenv: [py3]
        exclude:
          - os: ubuntu-latest
            python: "3.13"
            toxenv: py3
        include:
          - os: ubuntu-latest
            python: "3.13"
            toxenv: cover
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Configure Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Run tox
        run: uvx --with tox-uv tox -e ${{ matrix.toxenv }}
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results-${{ matrix.os }}-${{ matrix.python }}
          path: |
            junit/*.xml
      - name: Publish coverage
        uses: codecov/codecov-action@v5
        if: ${{ matrix.toxenv == 'cover' }}
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build docker image
        run: |
          set -euo pipefail
          COMMIT=$(git rev-parse --short=7 HEAD)
          DATE=$(date -u +%Y%m%d)
          # build image with a temp tag used by tests
          docker build -t adferrand/dnsrobocert:temp .
          # add informative tags: latest, commit hash, date, date_commit
          docker tag adferrand/dnsrobocert:temp adferrand/dnsrobocert:latest
          docker tag adferrand/dnsrobocert:temp adferrand/dnsrobocert:${COMMIT}
          docker tag adferrand/dnsrobocert:temp adferrand/dnsrobocert:${DATE}
          docker tag adferrand/dnsrobocert:temp adferrand/dnsrobocert:${DATE}_${COMMIT}
      - name: Run docker unit tests
        run: |
          mkdir -p ./bin
          curl -fsSL https://goss.rocks/install | GOSS_DST=./bin sh
          GOSS_PATH=./bin/goss GOSS_SLEEP=5 GOSS_FILES_PATH=./test/goss ./bin/dgoss run adferrand/dnsrobocert:temp
  quality:
    strategy:
      matrix:
        toxenv: [flake8, mypy]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Configure Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run tox
        run: uvx --with tox-uv tox -e ${{ matrix.toxenv }}
  event-file:
    runs-on: ubuntu-latest
    steps:
      - name: Upload event file
        uses: actions/upload-artifact@v4
        with:
          name: event-file
          path: ${{ github.event_path }}
